pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                echo "This is build step"
                '''
            }
        }
        stage('Test') {
            steps {
                sh ' echo "This is test phase" '
            }

        }
        stage('Deliver') {
            steps {
                sh 'echo " This is Deliver" '
            }
        }
    }
}
